config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/orchestrator:
      branch: master
      repo: https://github.com/indigo-dc/orchestrator
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/orchestrator git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-alizarin-mist.sh
        container: qc.acc_pokey-sangria-mule
  QC.Doc:
    repos:
      github.com/indigo-dc/orchestrator find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-persimmon-axolotl.sh
        container: qc.doc_ready-olive-quokka
      github.com/indigo-dc/orchestrator git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-jade-sponge.sh
        container: qc.doc_geeky-ultramarine-audemer
      github.com/indigo-dc/orchestrator markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tomato-rottweiler.sh
        container: qc.doc_pokey-corn-setter
  QC.Lic:
    repos:
      github.com/indigo-dc/orchestrator licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-sapphire-insect.sh
        container: qc.lic_trippy-olivine-crane
  QC.Sty:
    repos:
      github.com/indigo-dc/orchestrator checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-ecru-abyssinian.sh
        container: qc.sty_queasy-lemon-chamois
      github.com/indigo-dc/orchestrator hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-white-skunk.sh
        container: qc.sty_bumpy-ochre-audemer
      github.com/indigo-dc/orchestrator jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-bronze-wildebeest.sh
        container: qc.sty_freaky-lime-bulldog
  QC.Ver:
    repos:
      github.com/indigo-dc/orchestrator get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-aquamarine-macaque.sh
        container: qc.ver_chummy-turquoise-drever
timeout: 1800
