config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/orchestrator:
      branch: master
      repo: https://github.com/indigo-dc/orchestrator
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/orchestrator git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-olive-deer.sh
        container: qc.acc_queasy-crimson-frise
  QC.Doc:
    repos:
      github.com/indigo-dc/orchestrator find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-platinum-barracuda.sh
        container: qc.doc_stealthy-ivory-serval
      github.com/indigo-dc/orchestrator git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-vermilion-crab.sh
        container: qc.doc_cozy-flax-snake
      github.com/indigo-dc/orchestrator markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-ruby-liger.sh
        container: qc.doc_cozy-fuchsia-cow
  QC.Lic:
    repos:
      github.com/indigo-dc/orchestrator licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cobalt-audemer.sh
        container: qc.lic_stuffy-salmon-beagle
  QC.Ver:
    repos:
      github.com/indigo-dc/orchestrator get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-turquoise-labradoodle.sh
        container: qc.ver_muggy-sangria-husky
timeout: 1800
