config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/indigo-dc/orchestrator:
      branch: master
      repo: https://github.com/indigo-dc/orchestrator
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/indigo-dc/orchestrator git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-vermilion-donkey.sh
        container: qc.acc_geeky-wheat-affenpinscher
  QC.Doc:
    repos:
      github.com/indigo-dc/orchestrator find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-denim-gecko.sh
        container: qc.doc_pasty-cyan-avocet
      github.com/indigo-dc/orchestrator git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-grey-quail.sh
        container: qc.doc_cozy-peach-quokka
      github.com/indigo-dc/orchestrator markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cardinal-zonkey.sh
        container: qc.doc_skinny-yellow-magpie
  QC.Lic:
    repos:
      github.com/indigo-dc/orchestrator licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-yellow-neanderthal.sh
        container: qc.lic_wimpy-asparagus-corgi
  QC.Sty:
    repos:
      github.com/indigo-dc/orchestrator checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cerulean-crane.sh
        container: qc.sty_tacky-khaki-coati
      github.com/indigo-dc/orchestrator hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-violet-grasshopper.sh
        container: qc.sty_crabby-harlequin-camel
      github.com/indigo-dc/orchestrator jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-orchid-bird.sh
        container: qc.sty_beady-lilac-tang
  QC.Ver:
    repos:
      github.com/indigo-dc/orchestrator get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-violet-ibis.sh
        container: qc.ver_surly-sepia-nightingale
timeout: 1800
